### ISSUE TITLE
总体完美 一些细节优化建议

### ISSUE THREAD

**Issue by fanaruto** [nuanxinqing123/QLTools#10]
- [x] 下拉框：

![image](https://user-images.githubusercontent.com/45444732/166303374-00b75d4b-5b79-4b79-8cc3-1487b268d169.png)
可以调下大小边距 参考ElementUI样式[https://element.eleme.cn/#/zh-CN/component/dropdown](url)

- [ ] 管理面板：切换各项路由的时候会很明显的全屏闪一下，好像全屏刷新了 其实可以插入个加载动画然后只切换右边内容，左边导航栏不刷新

以上为一点建议 供暖心情🌤大佬参考

**Comment by nuanxinqing123** [comment]
关于下拉框的边距问题，受限于MDUI，无法做调整。管理面板的刷新问题也是因为卡元素问题，通过强制刷新来解决卡元素标签

**Comment by fanaruto** [comment]
> 
试下深度作用器更改样式 我看MDUI select 后面加个mdui-select的样式还可以 内置了一些小细节 ，那个样式内置边距好像

**Comment by fanaruto** [comment]
![image](https://user-images.githubusercontent.com/45444732/166400472-a7afba0d-1d03-4aa6-a0bc-1adafe08f574.png)
字体大小可以调整下 单独加个span标签 然后line-height调成和下拉框一样的高度  凸显标题，视觉效果会更棒
