### ISSUE TITLE
提交ck出错

### ISSUE THREAD

**Issue by ylegeb** [nuanxinqing123/QLTools#16]
![image](https://user-images.githubusercontent.com/62826329/168212685-9302ba2b-77fc-4744-b2fd-680810a4d9d6.png)
变量设置无误，符合正则，面板链接测试正常。
![image](https://user-images.githubusercontent.com/62826329/168212977-749e0fb0-7443-49a3-8429-cad0b71bf1fb.png)
日志报错【record not found】，tools在我使用cloudflared tunnle之前是可以用的，会是这个的问题吗？

**Comment by nuanxinqing123** [comment]
这是一个未知的错误，可以在TG联系我处理
