### ISSUE TITLE
提交CK严重错误

### ISSUE THREAD

**Issue by KosLzz** [nuanxinqing123/QLTools#17]
![1](https://user-images.githubusercontent.com/47625542/168883006-23cb8865-ae23-4419-a8b2-e4d7a551ac8a.png)

**存在问题:
按示例填写"某东的正则表达式（举例）：pt_key=.*?pt_pin=.*?;     【更新模式正则：pt_pin=.*?】"(如图)👆
Tools主页提交CK并不是提交到环境变量末尾,而是自动删除并替换对应青龙面板环境变量的首位CK**

![2](https://user-images.githubusercontent.com/47625542/168884254-12ffe517-fc06-4796-ba7e-a93741f78fee.png)

**Comment by nuanxinqing123** [comment]
青龙Tools V1.3 Bate_A 测试版已发布，可以尝试更新后，按照示例重新填写正则再尝试
