### ISSUE TITLE
变量超过九个后继续绑定新增变量不成功

### ISSUE THREAD

**Issue by penhuowa** [nuanxinqing123/QLTools#18]
青龙版本：2.12.2
qlTools版本：V1.3
BUG：当变量数量超过9后，继续绑定新增变量，却出现提示成功实际没有绑定的问题。
F12代码：
`"enablePanel":true,"envBinding":"0111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111122223456789"`

**Comment by nuanxinqing123** [comment]
已修复
