### ISSUE TITLE
求增加http://ip:15000/v1/api/index/data的响应时间

### ISSUE THREAD

**Issue by penhuowa** [nuanxinqing123/QLTools#19]
春川甲骨文其实延迟很低了，其他都没问题就这个数据响应超时，下个版本求增加响应时间，哪怕多一秒呢，方便一下国外服务器的孩子...![image](https://user-images.githubusercontent.com/51197099/169695900-425e71f6-f75f-4037-8af9-be631e8c4290.png)

**Comment by nuanxinqing123** [comment]
已增加
