### ISSUE TITLE
路径不能有大写字母，盘符自带就是大写的呢。。。

### ISSUE THREAD

**Issue by 664873568** [nuanxinqing123/QLTools#20]
$ docker run -itd --name QLTools -v $PWD/config:/QLTools/config -v $PWD/plugin:/QLTools/plugin -p 15000:15000 nuanxinqing123/qltools:latest
D:\Program Files\Docker Toolbox\docker.exe: invalid reference format: repository name must be lowercase.
See 'D:\Program Files\Docker Toolbox\docker.exe run --help'.

**Comment by nuanxinqing123** [comment]
这个属于Docker的限制，不在程序问题范围之类。启动时盘符是可以小写的
