### ISSUE TITLE
提交界面切换选项剩余位置没法同步变化

### ISSUE THREAD

**Issue by tlxhl** [nuanxinqing123/QLTools#3]
假设有服务器A和B，A绑定了京东变量，限额999，B只绑定了快手极速版变量，限额99。跳转提交界面的时候服务组是A，剩余位置假设是999，但当切换服务组为B时，剩余位置还是显示999，并没有变成99，而且因为服务器B只绑定了一个变量，所以不能通过切换变量组来刷新剩余位置，点击刷新面板按钮还是会回到服务组A。因为不能刷新剩余位置，所以就算CK、服务组、变量组都正确还是会显示提交服务器或变量名不在白名单中。

**Comment by nuanxinqing123** [comment]
已修复
