### ISSUE TITLE
希望增加JS脚本中正则匹配功能，同时希望能增加一些简单的JS模板或者api文档。

### ISSUE THREAD

**Issue by ShiJiDong** [nuanxinqing123/QLTools#31]
现在羊毛脚本所需CK格式都比较严格，抓包抓到的CK，是完整的CK。手动处理更改格式很不方便，很大几率还会改错。希望在JS脚本中可以匹配正则。这样正则来匹配、合并处理完整CK，网页只需要提交完整CK就可以。大大减小工作量。

**Comment by Bet5521** [comment]
这个是可以自己改造的，比如我自己就改了一下官方库里的美团CK检测插件，实现了，提交全CK，自动校验有消息，有效时将全CK中的token或者token2截取下来，传入meituanCookie变量上。实现了，提交饿了么全CK，自动校验有效性，有效时将全CK中的SID和cookie2截取下来，传入elmck变量上。
其他的一样可以类似操作。

**Comment by souying** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
