### ISSUE TITLE
【需求】希望能在变量提交下面添加个京东资产查询模块✨

### ISSUE THREAD

**Issue by hqw567** [nuanxinqing123/QLTools#35]
- **类似saobing的本地查询**
  - 用户提交京东CK后,把ck保存在浏览器本地存储
  - 本地有京东CK，打开网页就自动或用户手动查询京东资产
  - 如本地京东CK失效了，提示用户更新或提交京东变量，再更新本地京东ck后，再重新查询资产
- 多账号用户 放个入口，让用户自行提供需要查询资产的ck，查询

**Comment by nuanxinqing123** [comment]
暂时不针对此类功能进行开发
