### ISSUE TITLE
设置背景图后，界面的部分模块看不清

### ISSUE THREAD

**Issue by Hyouka0510** [nuanxinqing123/QLTools#42]
背景图：https://s1.ax1x.com/2022/06/20/Xv8iy8.jpg

后台效果：（主要是左侧菜单看不清）
![sWUjZ.png](https://s1.328888.xyz/2022/06/22/sWUjZ.png)
前台效果（登录）（网站标题和右上角图标）：
![sW2vA.png](https://s1.328888.xyz/2022/06/22/sW2vA.png)
前台效果（未登录）（网站标题和右上角图标）：
![sWrIm.png](https://s1.328888.xyz/2022/06/22/sWrIm.png)

**Comment by nuanxinqing123** [comment]
推荐更新其他浅色壁纸，适配深色壁纸比较麻烦
