### ISSUE TITLE
服务器、变量组、剩余位置都是空白的，不晓得是不是安装的有错

### ISSUE THREAD

**Issue by showlee** [nuanxinqing123/QLTools#48]
群晖NAS上安装后，xxxx:15000/#/register注册后登陆，服务器、变量组、剩余位置都是空白的。
这是怎么回事？不晓得应该怎么做？
![image](https://user-images.githubusercontent.com/20532746/177071567-b74547bb-1914-4ce4-8dcd-8639c2629793.png)

**Comment by hyf0988** [comment]
我的DS6.2.3装完也是这样

**Comment by nuanxinqing123** [comment]
有没有一种可能，你没有登入后台填写变量规则和连接面板相关的信息呢
