### ISSUE TITLE
CK过长时提示发生一点小意外请重新提交

### ISSUE THREAD

**Issue by jingjingfq** [nuanxinqing123/QLTools#49]
QLtools：1.9
QL：2.12.1
特别是饿了么，58同城这种CK巨长的，一个多月前就有这种情况了，长CK提交不了，把CK删短了就能提交

**Comment by nuanxinqing123** [comment]
暂时未测试出相关的Bug，你可以尝试使用正则表达式过滤出需要的变量值来提交（缩短变量值长度）
