### ISSUE TITLE
QLTools或者PRO版本，插件支持备注信息的检测吗？

### ISSUE THREAD

**Issue by Bet5521** [nuanxinqing123/QLTools#57]
如题
QLTools或者PRO版本，插件支持备注信息的检测吗？
我看了普通版和PRO版的插件说明，都没有写备注信息的检验和写入功能，如果支持是否有简单说明或者方法调用？

**Comment by shixiangkuangmo** [comment]
> 如题 QLTools或者PRO版本，插件支持备注信息的检测吗？ 我看了普通版和PRO版的插件说明，都没有写备注信息的检验和写入功能，如果支持是否有简单说明或者方法调用？

同问

**Comment by nuanxinqing123** [comment]
开源版和Pro版本均不支持
