### ISSUE TITLE
如何设置备注必填，且在青龙里拿到备注？

### ISSUE THREAD

**Issue by shixiangkuangmo** [nuanxinqing123/QLTools#64]
如何设置备注必填，且在青龙里拿到备注？

**Comment by souying** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by nuanxinqing123** [comment]
> 如何设置备注必填，且在青龙里拿到备注？

目前的逻辑不支持
