### ISSUE TITLE
CK提交后清空输入框，剩余位置-1

### ISSUE THREAD

**Issue by HenMie** [nuanxinqing123/QLTools#7]
并且可考虑增加：后台设置浮动提示或弹窗提示
提交成功的提示会更加明显

**Comment by nuanxinqing123** [comment]
描述问题请带上截图

**Comment by HenMie** [comment]
> 描述问题请带上截图

不是问题啦，建议一下

**Comment by nuanxinqing123** [comment]
CK提交后清空输入框，剩余位置-1

你标题这个不是问题吗？

**Comment by nuanxinqing123** [comment]
弹窗提示 不错，可以改为弹窗。提示性更强

**Comment by nuanxinqing123** [comment]
提交成功后清空输入栏可以处理，但是剩余位置-1是一个不合适的需求。为什么要-1呢？

**Comment by HenMie** [comment]
> 什么要-1呢？

就是指前台显示的-1，目前提交成功之后，显示位置还是不变的，需要刷新才改变。改一下前台显示更直观吧

**Comment by HenMie** [comment]
不是指总位置-1，只是提交成功后的前端展示

**Comment by nuanxinqing123** [comment]
已增加，前端数据变化等待后续版本更新
