### ISSUE TITLE
ck只能新增不能更新？

### ISSUE THREAD

**Issue by hdstar2009** [nuanxinqing123/QLTools#8]
原本已经在ql容器中的ck（已失效）提交更新的ck发现只能作为新ck新增到ql环境变量中而不是更新已失效的同pinck？
是我哪操作不对还是bug？

**Comment by nuanxinqing123** [comment]
不可以更新，目前只有新增和合并两种模式。后续会考虑如何插入更新的判断条件，如果有好的思路请留言
